### ISSUE TITLE
equality

### ISSUE THREAD

**Issue by borkdude** [clavascript/clavascript#1]
What should `(= x y)` compile into?

**Comment by brandonstubbs** [comment]
I would say [Strict equality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality)
https://stackoverflow.com/questions/359494/which-equals-operator-vs-should-be-used-in-javascript-comparisons

**Comment by borkdude** [comment]
Yep, mapped it to `===` now.
