### ISSUE TITLE
Exclude core exports

### ISSUE THREAD

**Issue by lilactown** [clavascript/clavascript#134]
Currently, we can't prevent exports from `core.js` from being automatically imported into a module

Given the code:

```clojure
(clava.transducers
  (:refer-clojure :exclude [map]))
,,,
(defn map
  [f]
  (fn [rf]
    (->Mapping f rf)))
```

Results in

```javascript
import { map } from 'clavascript/core.js'

var map = function (f) {
return function (rf) {
return __GT_Mapping(f, rf);
};
```

Which when run throws `SyntaxError: Identifier 'map' has already been declared`.

---

I'm not beholden to any syntax (does using `:refer-clojure` make sense?) but it would be nice to be able to do this.

**Comment by borkdude** [comment]
Yes, let's do `:refer-clojure` so clj-kondo will also understand.
