### ISSUE TITLE
equal? predicate for structural equality

### ISSUE THREAD

**Issue by borkdude** [clavascript/clavascript#16]
We could support `(ns foo (:require [clava.core :refer [equal?]]))` as a synonym for `(:require ["clavascript/core.js" :refer [equal?]])`.

`equal?` works on nested arrays, objects and sets and falls back to `===` for other types.

When comparing two objects, first it should be determined if they are of the same type using `instanceof` (or so) and then we should defer to helper functions which efficiently check the contents of two things of the same type, e.g. `arrayEquals`, `setEquals`. A quick first check is to check if the length of the two objects are the same, before traversing the object.

**Comment by corasaurus-hex** [comment]
I think it's safe to say that in js-land there are _a lot_ of corner cases for equality testing and it would be worth exploring some of the prior art to look for these cases.

* https://github.com/inspect-js/node-deep-equal
* https://lodash.com/docs/4.17.15#isEqual
* https://underscorejs.org/#isEqual
* https://github.com/epoberezkin/fast-deep-equal

**Comment by borkdude** [comment]
That's indeed a loooot of corner cases. Enough reason to not take on this complexity here.
