### ISSUE TITLE
Garbage collection with lazy seqs not working properly

### ISSUE THREAD

**Issue by borkdude** [clavascript/clavascript#160]
Repro. With a true "cons" cell, and the function `rest2` you can see that the giant array which is the head of the cons, is freed. But when changing to `rest` from clava, memory stays occupied. /cc @lilactown 

``` javascript
// run with: node --expose-gc mem.js

import { rest, first, list } from './core.js';

class Cons {
  constructor(head, tail) {
    this.head = head;
    this.tail = tail;
  }
  *[Symbol.iterator]() {
    yield this.head;
    if (this.tail)
      yield* this.tail;
  }
}

function cons(head, tail) {
  return new Cons(head, tail);
}

function rest2(theCons) {
  return theCons.tail;
}

global.gc();

console.log(process.memoryUsage());

var y = cons(new Array(10000000).fill(0), cons(1, null));

global.gc();

console.log(process.memoryUsage());

y = rest2(y);

console.log([...y]);

global.gc();

console.log(process.memoryUsage());
```

**Comment by borkdude** [comment]
@lilactown Perhaps this would be a reason to introduce a true `Cons` and a `LazySeq` data structure. This will ensure GC and also caching at the same time.

**Comment by borkdude** [comment]
Hmm, before we go there, maybe `rest` needs a little bit more debugging to see why the first element of the array is being held on to.

**Comment by lilactown** [comment]
Paring the example down to just

```javascript
global.gc();

console.log(process.memoryUsage());

var y = new Array(10000000).fill(0);

console.log(process.memoryUsage());

global.gc();

console.log(process.memoryUsage());
```

Shows a close memory usage as the current `rest` / `cons` approach. I don't understand why yet.

**Comment by borkdude** [comment]
Because you have to set `y` to `null` in order for it to be garbage collected.

**Comment by borkdude** [comment]
@lilactown I changed `rest` locally to:

```
export function rest(coll) {
  return new LazyIterable(function* () {
    let iter = coll[Symbol.iterator]();
    iter.next();
    coll = null;
    for (const x of iter) {
      yield x;
    }
  });
}
```

This seems to exhibit the desired behavior.

**Comment by borkdude** [comment]
This may be because Node.js doesn't have locals-clearing.

**Comment by borkdude** [comment]
So I think in general, once we have the iterator, we can let go of the original collection by setting the argument to `null`.

**Comment by lilactown** [comment]
If you clear the argument, you can't reuse the iterable. Using the implementation you provided:

```
$ node
> let core = import('./core.js').then((m) => { core = m })
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 698,
  [Symbol(trigger_async_id_symbol)]: 682
}
> let a = [1, 2, 3];
undefined
> let b = core.rest(a)
undefined
> core.vec(b);
[ 2, 3 ]
> core.vec(b);
[]
```

**Comment by borkdude** [comment]
Hmm, darn.

**Comment by borkdude** [comment]
I see two directions then: either go back to only eager stuff based on concrete arrays, or implement the ISeq abstraction with `first` and `rest` using `Cons`, `List`, `LazySeq` etc.

Or we could depend on some third party library like immutable.js for this, which might not be great.

**Comment by lilactown** [comment]
Is this similar to what you mean by `implement the ISeq abstraction` https://github.com/clavascript/clavascript/compare/main...lilactown:clavascript:lilactown/better-cons

**Comment by borkdude** [comment]
Yes, kind of, but I think `map` and other seq-functions should then return something which fulfills the ISeq protocol so we can reliably get rid of the head and return the rest, while also having caching, like you would expect from CLJS.

**Comment by borkdude** [comment]
Or a third option: accept this behavior.

**Comment by lilactown** [comment]
Caching and cleaning the generator function in the LazyIterable seems GC the head when used with `rest`: https://github.com/clavascript/clavascript/compare/main...lilactown:clavascript:lilactown/caching-lazy-iterable

**Comment by lilactown** [comment]
Adding this as a reminder to check how it interacts with ‘first’

**Comment by borkdude** [comment]
@lilactown So the caching would kick in once you have realized the whole iterator. And then there's an array which holds on to the entire "rest". What if you apply rest twice? `(rest (rest [big-array, big-array, 1]))`, would GC work there?

**Comment by borkdude** [comment]
I tested with `(rest (rest ..))` and it seems to work GC-wise.

**Comment by borkdude** [comment]
So with partially realized sequences you would still get:

```
$ ./node_cli.js -e '(def mapping (map #(doto % prn) (range))) (prn (take 2 mapping)) (prn (take 2 mapping))'
0
1
2
[0,1]
0
1
2
[0,1]
```

but once fully realized:

```
$ ./node_cli.js -e '(def mapping (map #(doto % prn) (range))) (def take2 (take 2 mapping)) (prn take2) (prn take2)'
0
1
2
[0,1]
[0,1]
```

It might be a reasonable compromise, yet it would be more optimal if partial results could also be cached.

**Comment by borkdude** [comment]
@lilactown I thought about this some more and caching (building up arrays) is a disadvantage when you work with multiple intermediate seqs like `(->> (range) (map inc) (filter odd?) (first))`. Perhaps we should just add documentation about the GC caveat.

E.g. this works fine:

``` javascript
import { rest, first } from './core.js';

global.gc();

console.log(process.memoryUsage());

function doit () {
  var y = [new Array(10000000).fill(0), 1, 2, 3];
  return first(rest(y));
}

console.log(doit());

global.gc();

console.log(process.memoryUsage());
```

The recommendation should probably be: keep the usage of lazy sequences local to a function and don't let laziness escape a function (if they contain big resources): return a concrete result (single value or an array).

**Comment by lilactown** [comment]
@borkdude I had a big long post that got lost when I restarted my machine. Essentially laying out the caveats since yeah, that commit only caches if you realize the full seq.

There's an interplay with caching and mutability which I'm struggling with too. E.g. if you have a lazy iterable based on an array, and in between subsequent calls to `first` / `rest` that array is mutated, what should happen?

Without caching you always get the current view on the array. If you cache, you want to know explicitly when something is cached so that you can reason about the value of the seq in relation to the value of the array it's wrapping.

Something comes to mind... in Clojure, it's somewhat common to wrap lazy seqs in `doall` when one wants to explicitly realize it. Perhaps `doall` could return a concrete collection (i.e. an array), and we can recommend a pattern that is: don't leak lazy iterables, call `doall` before returning it.

**Comment by borkdude** [comment]
Yes, I was thinking `doall` and `vec` should just be a synonym for each other.

**Comment by borkdude** [comment]
@lilactown I added this to the README: https://github.com/clavascript/clavascript#memory-usage
