### ISSUE TITLE
take is too eager

### ISSUE THREAD

**Issue by borkdude** [clavascript/clavascript#162]
Repro:

```
$ ./node_cli.js -e '(prn (take 2 (map #(doto % prn) (range))))'
0
1
2
[0,1]
```

I think `map` should not realize more than two items here.

OTOH: CLJS is much more eager, due to chunking it realizes 32 items at once.

**Comment by lilactown** [comment]
This is a problem with `take` actually

**Comment by borkdude** [comment]
Aha!
