### ISSUE TITLE
Maps & complex keys

### ISSUE THREAD

**Issue by lilactown** [clavascript/clavascript#4]
Currently, clavascript maps are compiled to JS objects. This works fine as long until you need complex keys, e.g.

```clojure
{[:foo "123"] {:foo/id "123" :bar "baz"}}
```

In the above case, the vector is used as a key. JS objects only support string keys.

**Comment by borkdude** [comment]
I think if you really need this, you should create a `js/Map`. Clava defaults to JS objects because they are so ubiquitous and it makes interop a lot easier. What do you think?

```
$ npx clava -e '(println (js/Map. [[[:foo "123"] {:foo/id "123" :bar "baz"}]]))'
Map(1) { [ 'foo', '123' ] => { id: '123', bar: 'baz' } }
```

**Comment by borkdude** [comment]
We could come up with a convenience like a data reader to turn map notation into a js/Map though. Like `#js/map {:a 1}`.
