### ISSUE TITLE
get - edge cases

### ISSUE THREAD

**Issue by brandonstubbs** [clavascript/clavascript#80]
There are corner cases that can fail in the current implementation of `get`, and I am happy to do a PR.
```
# ./node_cli.js --show -e '(get nil nil)'                           
import { get } from 'clavascript/core.js'
get(null, null);

file:///Users/brandonstubbs/projects/clojure/clavascript/core.js:227
  return key in coll ? coll[key] : otherwise;
             ^

TypeError: Cannot use 'in' operator to search for 'null' in null
...
```

We can fix the `get` on a `nil` easily, but there are a few more edge cases:
```clojure
;; array with nil
(get "1" nil) ;; => "1"
(get [1 2 3] nil) ;; => nil
(get (array 1 2 3) nil) ;; => 1
;; when `k` is an `array` or `string` it gets called as `(int k)` in clojurescript => `(int nil) => 0`

;; keyword, as this would be a string internally, so clava would return "f"
(get :foo nil) ;; => nil 
```

How do we want to handle these in clava?

**Comment by borkdude** [comment]
> (get "1" nil) ;; => "1"

This should return `nil`, I think? Or am I missing something?

**Comment by brandonstubbs** [comment]
[`(int nil) ;; => 0`](https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/core.cljs#L1968)

**Comment by borkdude** [comment]
`get` in Clojure/Script works on associative collections, but CLJS doesn't coerce the "key" to an `int`. Why do you think Clava should do so? I would find that confusing. When I evaluate this in a Node.js REPL:

```
 "foo"[null]
```

I get `undefined`.

**Comment by brandonstubbs** [comment]
Ah you're right! 🙈 I jumped into a repl on an old project which had version `1.9.229` with the issue, that's my bad!

Will do the fix
