### ISSUE TITLE
Macroify: nth

### ISSUE THREAD

**Issue by lilactown** [clavascript/clavascript#9]
`nth` should emit code the same as `unchecked-get`:

```clojure
(nth [1 2 3] 2)
```

```javascript
([1, 2, 3][2])
```

**Comment by lilactown** [comment]
This is actually a little trickier than I originally thought. The issue is that `nth` in Clojure supports `nil`, which we need for safe destructuring:

```clojure
(let [[foo bar] nil]
  foo)
```

Is a perfectly valid bit of code, but would fail if we translated it to

```javascript
(function () {
  let foo = null[0];
  let bar = null[1];
  return foo;
})()
```

**Comment by borkdude** [comment]
Yeah, maybe this isn't worth the risk of breakage. I'll close this for now.
